# Use a Node.js base image for building the React app
FROM node:latest as build-stage

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json to the working directory
COPY package.json ./

# Install the dependencies
RUN npm install

# Copy the client files to the working directory
COPY . .

# Build the client
RUN npm run build

# Use Nginx as the production server
FROM nginx:latest

# Copy the built React app from the build-stage to Nginx's default public directory
COPY --from=build-stage /usr/src/app/dist /usr/share/nginx/html

# Expose the default Nginx port
EXPOSE 80

# Start Nginx when the container starts
CMD ["nginx", "-g", "daemon off;"]
